Country field added for international schools
cs169/BJC-Teacher-Tracker-App pull request #42
Opened 2024-03-12 00:13 UTC by razztech

### [Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187216522)

[tracker]: https://www.pivotaltracker.com/story/show/your-story-id

## What this PR does:
This PR adds the country field to the school model. Whenever a new school is created, the option to select a country is available. Moreover, the country data is introduced in tables, teacher and school information panels and in the backend. The UI logic either renders a textfield if the country selected when creating a school is not the US or a dropdown of US states if the selected country is the US. 

### Include screenshots
<img width="1695" alt="Screenshot 2024-03-11 at 5 02 43 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/b43bf02f-d1f6-4dbb-a3b7-663f1d1e518a">
<img width="1046" alt="Screenshot 2024-03-11 at 5 03 08 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/8abe0f8d-0b0c-4153-acd3-57f80afdc742">
<img width="1720" alt="Screenshot 2024-03-11 at 5 03 15 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/4b3e4907-a599-4286-8cb2-2e0983f6c8fc">
<img width="1714" alt="Screenshot 2024-03-11 at 5 03 28 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/559cfa45-28f3-4a3b-9dcc-aeb69bc7d5b6">
<img width="1720" alt="Screenshot 2024-03-11 at 5 03 37 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/5154b291-575c-49f2-8b3c-1d34e20350fa">
<img width="1098" alt="Screenshot 2024-03-11 at 5 04 43 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/95bc20a2-6f93-450b-a58e-eedc55fc88b2">
<img width="1110" alt="Screenshot 2024-03-11 at 5 04 56 PM" src="https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/69b24dd7-198c-4a25-bd6d-c588b9c7ed94">

### Who authored this PR?
- @razztech overall implementation, testing, code refactoring and UI logic
- @perryzjc pair-programming help for debugging teacher requests table

### How should this PR be tested?
1. Create a new request as a teacher 
2. Input a school that is not present in the dropdown and click enter 
3. Select the country of your choice outside the US and type a random state in the State field
4.  Submit your request. 
5. Login as an admin and see that the country selected and the state are present in the data. 

### What do the specs/features test?
- The feature tests if there is a country outside of the US selected then we should be able to type in the name of the state for that country instead of selecting from the usual US states dropdown. 

### Are there edge cases to watch out for?
No.

### Migration
20240307225738_add_country_to_schools.rb = adds the country field to the school model;

### Checklist:

- [x] Has this been deployed to a staging environment or reviewed by a customer?
- [x] Tag someone for code review (either a coach / team member)
- [x] I have renamed the branch to match PivotTracker's suggested one (necessary for BlueJay) (e.g. `michael/12345-add-new-feature` Any branch name will do as long as the story ID is there. You can use `git checkout -b [new-branch-name]`)

2024-03-12 02:16 UTC, perryzjc commented
@razztech Nice job! This is a significant amount of work. I have a few notes for this PR:

1. Based on the code review Michael provided during today's lecture (Mar 11), he mentioned that it might be better not to include customized steps within `web_steps.rb`. Instead, it's recommended to place them in a separate customized steps file. `form_steps.rb` might be the ideal one for the case for this PR.

2. Depending on Michael's preferences, it might be more comprehensive to include tests like `I should see "AL"` to verify the existence of the new country field for both the teacher and school tabs.

3. This PR could benefit from more detailed documentation:
   - You already mentioned `20240307225738_add_country_to_schools.rb = adds the country field to the school model;` but it might be clearer to explicitly mention running `rails db:migrate` for it.
   - Additionally, since this PR introduces new Gem files, it would be helpful to include instructions to run `bundle install`.

4. Some clarifications might be needed from Michael:
   - When the country field is displayed, do we want it in abbreviated form or in full form? For example, should it be 'China' or 'CN'? The current version is only displaying the abbreviated form, such as `AL` and `RO`, which might not be very readable:

   ![image](https://github.com/cs169/BJC-Teacher-Tracker-App/assets/92573736/dd88cce4-f532-4cd4-b611-af9811b44d30)

2024-03-12 03:15 UTC, fp456 commented on app/models/school.rb
> +  validates :state, presence: true, if: -> { country == "US" }
Maybe swap 33 and 32, validate for presence first and then for inclusivity

2024-03-12 03:16 UTC, fp456 commented on app/models/school.rb
> +  validates :name, :city, :website, :country, presence: true
Is country a dropdown? If not, it may be necessary to check for the validity of that input. If not, ignore this comment 👍

2024-03-12 03:21 UTC, fp456 commented on features/school_form_submission.feature
Nice tests! Is it possible to come up with a test that tests undesired user behaviour? For example, something that will result into an error raised, or other behavior that will trigger an unhappy path.

2024-03-12 03:22 UTC, fp456 commented on features/teacher.feature
>    # TODO: Should this test updating to a new school?
cleaning: remove comment

2024-03-12 03:25 UTC, fp456 requested changes
Good job! It seems very good overall 🙌 just some tiny things here and there regarding testing and some clean up.

2024-03-12 17:15 UTC, perryzjc commented
Review notes for today's customer meeting with Michael:

1. Put LOCATION AND COUNTRY TOGETHER.
2. School name should take up the entire row on the screen (on the new school page).
3. City, state, country (in that order) should occupy the entire row on the screen (on the new school page).
4. Default to US.

2024-03-13 17:43 UTC, razztech commented
![Screenshot 2024-03-13 at 10 43 51 AM](https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/ca1aefcd-eb79-4943-a474-b0c73544c4ac)

2024-03-13 17:45 UTC, razztech commented
![Screenshot 2024-03-13 at 10 44 57 AM](https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/0a9ce421-cb58-4924-a820-d8c9b4bf9c9b)
![Screenshot 2024-03-13 at 10 45 09 AM](https://github.com/cs169/BJC-Teacher-Tracker-App/assets/41014369/7a3295c0-ea17-4bb4-8700-a4c3b50f49ce)

2024-03-13 17:55 UTC, ArushC commented
@razztech LGTM. Just for future reference, I find it helpful to use the $(...) jQuery notation when writing Javascript. I asked ChatGPT to rewrite your JS code using $(...) stuff and this is what it came up with:

<script>
  $(document).ready(function() {
    const countrySelected = $('#school_country');
    const stateSelectContainer = $('#state_select_container');
    const stateTextfieldContainer = $('#state_textfield_container');
    const stateSelect = $('#state_select');
    const stateTextfield = $('#state_textfield');

    function handleCountryChange() {
      if (countrySelected.val() === 'US') {
        stateSelectContainer.show().attr('required', true);
        stateTextfieldContainer.hide();

        stateTextfield.removeAttr('name'); 
        stateSelect.attr('name', 'school[state]');
      } else {
        stateTextfieldContainer.show().attr('required', false);
        stateSelectContainer.hide();

        stateSelect.removeAttr('name');
        stateTextfield.attr('name', 'school[state]');
      }
    }
    countrySelected.change(handleCountryChange);
    handleCountryChange(); 
  });
</script> 

 Idk if it works, but if you want you can test it. Personally, I think it's a lot easier to read. I'm going to wait for someone else to review changes before merging because I'm not 100% confident I understand everything that's going on here. @perryzjc you should probably review.

2024-03-13 23:30 UTC, perryzjc commented
> @razztech LGTM. Just for future reference, I find it helpful to use the `$`(...) jQuery notation when writing Javascript. I asked ChatGPT to rewrite your JS code using $(...) stuff and see below for what it came up with. Idk if it works, but if you want you can test it. Personally, I think it's a lot easier to read. I'm going to wait for someone else to review changes before merging because I'm not 100% confident I understand everything that's going on here. @perryzjc you should probably review.
> 
> ```js
> <script>
>   $(document).ready(function() {
>     const countrySelected = $('#school_country');
>     const stateSelectContainer = $('#state_select_container');
>     const stateTextfieldContainer = $('#state_textfield_container');
>     const stateSelect = $('#state_select');
>     const stateTextfield = $('#state_textfield');
> 
>     function handleCountryChange() {
>       if (countrySelected.val() === 'US') {
>         stateSelectContainer.show().attr('required', true);
>         stateTextfieldContainer.hide();
> 
>         stateTextfield.removeAttr('name'); 
>         stateSelect.attr('name', 'school[state]');
>       } else {
>         stateTextfieldContainer.show().attr('required', false);
>         stateSelectContainer.hide();
> 
>         stateSelect.removeAttr('name');
>         stateTextfield.attr('name', 'school[state]');
>       }
>     }
>     countrySelected.change(handleCountryChange);
>     handleCountryChange(); 
>   });
> </script>
> ```

Just finished review. Looks to me as well, and I helped fix the reviews I came up, plus adding  a new test for undesired user behavior

2024-03-14 01:07 UTC, razztech commented
Thank you @perryzjc!

2024-03-14 03:51 UTC, merged